DATO 	EQU 0X21
CONR	EQU 0X22
CONE	EQU 0X23
MAYG	EQU 0X24 ; grupo mayor
MAYV	EQU 0X25 ; valor grupo mayor
MENG	EQU 0X26 ; grupo menor
MENV	EQU 0X27 ; valor grupo menor
;**********valores de backup
MAYBG	EQU 0X28 ; grupo mayor backup
MAYBV	EQU 0X29 ; valor grupo mayor backup
MENBG	EQU 0X30 ; grupo menor backup
MENBV	EQU 0X31 ; valor grupo menor backup
;****************************
d1	EQU 0X32
d2	EQU 0X33
d3	EQU 0X34



INICIO
	BSF ADCON0, GO_DONE
	ORG 0X00 
	GOTO START
	
START
	; siempre debemos modificar el registro status antes de utilizar los puertos
	BSF	STATUS, 5 
	;BSF	TRISB, 0 ; env�a datos
	BSF	TRISD,6 ;************************
	;BCF	TRISB, 1
	;BCF	TRISB, 2
	;BCF	TRISB, 3
	;BCF	TRISB, 4
	BCF	TRISC, 4 ;************************
	BCF	TRISC, 5 ;************************
	BCF	TRISC, 6 ;************************
	BCF	TRISC, 7 ;************************

	BSF	TRISC, 0 ; BIT 0 recibir
	BSF	TRISC, 1 ; BIT 1 recibir
	BSF	TRISC, 2 ; BIT 2 recibir
	BSF	TRISC, 3 ; BIT 3 recibir
	BSF	TRISD, 0 ; identifica que tiene que recibir datos
	;BCF 	STATUS, RP0
	;MOVLW	B'00000000'
	;MOVWF	PORTB
	;MOVLW	B'00001110'
	;MOVWF	PORTC 	
	MOVLW   B'00000001'
	MOVWF	CONE
	MOVWF	CONR
	;MOVLW   B'00001000'	
	MOVWF	MAYG
	;MOVLW	B'00001001'
	MOVWF	MAYV
	;MOVLW	B'00001000'
	MOVWF	MENG
	;MOVLW	B'00001001'
	MOVWF	MENV
	;MOVLW	B'00000000'
	;MOVWF	MAYBG
	;MOVLW	B'00000000'
	;MOVWF	MENBG
	;MOVLW	B'00000000'
	;MOVWF	MAYBV
	;MOVLW	B'00000000'
	;MOVWF	MAYBV
		
MENU
	CALL	DELAY_D
	BTFSC   PORTB, 0 ; si el bit de enviar enta encendido va a enviar datos
	CALL	ENVIARDEC
	CALL	DELAY_D
	BTFSC	PORTD, 0
	CALL	RECIBIRDEC
	GOTO	MENU

ENVIARDEC ; Decide que enviar encicladamente
	CALL	DELAY_D
	MOVLW	B'00000001'
	SUBWF	CONE, 0
	BTFSC	STATUS, Z
	CALL	ENVIARGM ; enviar grupo mayor
	CALL	DELAY_D
	MOVLW	B'00000010'
	SUBWF	CONE, 0
	BTFSC	STATUS, Z
	CALL	ENVIARVM ; enviar valor mayor
	CALL	DELAY_D
	MOVLW	B'00000011'
	SUBWF	CONE, 0
	BTFSC	STATUS, Z
	CALL	ENVIARGMM ; enviar grupo menor
	CALL	DELAY_D
	MOVLW	B'00000100'
	SUBWF	CONE, 0
	BTFSC	STATUS, Z
	CALL	ENVIARVMM ; enviar valor menor
	CALL	DELAY_D
	MOVLW	B'00000101'
	SUBWF	CONE, 0
	BTFSC	STATUS, Z
	CALL	FINENV; hacer comparacion	
	INCF	CONE, 1	
	RETURN

SETBITS
	BTFSC	DATO, 0
	GOTO	SET11
	GOTO	SET10
SETBITS1
	BTFSC	DATO, 1
	GOTO	SET21
	GOTO	SET20
SETBITS2
	BTFSC	DATO, 2
	GOTO	SET31
	GOTO	SET30
SETBITS3
	BTFSC	DATO, 3
	GOTO	SET41
	GOTO	SET40
ENDSET
	RETURN	

SET11
	;BSF	PORTB, 1
	BSF	PORTC, 4 ;***************************
	GOTO	SETBITS1
SET10
	;BCF	PORTB, 1
	BSF	PORTC, 4 ;***************************
	GOTO	SETBITS1
	
SET21
	;BSF	PORTB, 2
	BSF	PORTC, 5 ;***************************
	GOTO	SETBITS2
SET20
	;BCF	PORTB, 2
	BSF	PORTC, 5 ;***************************
	GOTO	SETBITS2
	
SET31
	;BSF	PORTB, 3
	BSF	PORTC, 6 ;***************************
	GOTO	SETBITS3
SET30
	;BCF	PORTB, 3
	BSF	PORTC, 6 ;***************************
	GOTO	SETBITS3
	
SET41
	;BSF	PORTB, 4
	BSF	PORTC, 7 ;***************************
	GOTO	ENDSET
SET40
	;BCF	PORTB, 4
	BSF	PORTC, 7 ;***************************
	GOTO	ENDSET
	
ENVIARGM
	MOVF	MAYG, W
	MOVWF 	DATO
	CALL	SETBITS
	;BTFSC	PORTB, 0
	BTFSC	PORTD, 6 ;***********************
	GOTO	ENVIARGM 
	RETURN
	
ENVIARVM
	MOVF	MAYV, W
	MOVWF 	DATO
	CALL	SETBITS	
	;BTFSC	PORTB, 0
	BTFSC	PORTD, 6 ;***********************
	GOTO	ENVIARVM 
	RETURN
	
ENVIARGMM
	MOVF	MENG, W
	MOVWF 	DATO
	CALL	SETBITS	
	;BTFSC	PORTB, 0
	BTFSC	PORTD, 6 ;***********************
	GOTO	ENVIARGMM 
	RETURN
	
ENVIARVMM
	MOVF	MENV, W
	MOVWF 	DATO
	CALL	SETBITS	
	;BTFSC	PORTB, 0
	BTFSC	PORTD, 6 ;***********************
	GOTO	ENVIARVMM 
	RETURN

RECIBIRDEC ; recibe encicladamente
	CALL	DELAY_D
	MOVLW	B'00000001'
	SUBWF	CONR, 0
	BTFSC	STATUS, Z
	CALL	RECIBIRGM ; enviar grupo mayor
	CALL	DELAY_D
	MOVLW	B'00000010'
	SUBWF	CONR, 0
	BTFSC	STATUS, Z
	CALL	RECIBIRVM ; enviar valor mayor
	CALL	DELAY_D
	MOVLW	B'00000011'
	SUBWF	CONR, 0
	BTFSC	STATUS, Z
	CALL	RECIBIRGMM ; enviar grupo menor
	CALL	DELAY_D
	MOVLW	B'00000100'
	SUBWF	CONR, 0
	BTFSC	STATUS, Z
	CALL	RECIBIRVMM ; enviar valor menor	
	CALL	DELAY_D
	MOVLW	B'00000101'
	SUBWF	CONR, 0
	BTFSC	STATUS, Z
	CALL	FINREC; hacer comparacion	
	INCF	CONR, 1			
	RETURN
	
FINREC
	MOVLW	B'00000000'
	MOVWF   CONR
	CALL	COMPAREMAYORG
	CALL	COMPAREMENORG
	BTFSC	PORTD, 0
	GOTO	FINREC 
	RETURN
	
FINENV
	MOVLW	B'00000000'
	MOVWF   CONE
	;BTFSC	PORTB, 0
	BTFSC	PORTD, 6 ;****************************
	GOTO	FINENV
	RETURN
	
SET11R
	BSF	DATO, 0
	GOTO	SETBITS1R
SET10R
	BCF	DATO, 0
	GOTO	SETBITS1R
	
SET21R
	BSF	DATO, 1
	GOTO	SETBITS2R
SET20R
	BCF	DATO, 1
	GOTO	SETBITS2R
	
SET31R
	BSF	DATO, 2
	GOTO	SETBITS3R
SET30R
	BCF	DATO, 2
	GOTO	SETBITS3R
	
SET41R
	BSF	DATO, 3
	GOTO	ENDSETR
SET40R
	BCF	DATO, 3
	GOTO	ENDSETR

SETBITSR
	BTFSC	PORTC, 3
	GOTO	SET11R
	GOTO	SET10R
SETBITS1R
	BTFSC	PORTC, 2
	GOTO	SET21R
	GOTO	SET20R
SETBITS2R
	BTFSC	PORTC, 1
	GOTO	SET31R
	GOTO	SET30R
SETBITS3R
	BTFSC	PORTC, 0
	GOTO	SET41R
	GOTO	SET40R
ENDSETR
	RETURN	

	
RECIBIRGM
	CALL	SETBITSR
	MOVF	DATO, W
	MOVWF	MAYBG
	BTFSC	PORTD, 0
	GOTO	RECIBIRGM 
	RETURN	
	
RECIBIRVM
	CALL	SETBITSR
	MOVF	DATO, W
	MOVWF	MAYBV
	BTFSC	PORTD, 0
	GOTO	RECIBIRVM 
	RETURN

RECIBIRGMM
	CALL	SETBITSR
	MOVF	DATO, W
	MOVWF	MENBG
	BTFSC	PORTD, 0
	GOTO	RECIBIRGMM 
	RETURN	

RECIBIRVMM
	CALL	SETBITSR
	MOVF	DATO, W
	MOVWF	MENBV
	BTFSC	PORTD, 0
	GOTO	RECIBIRVMM 
	RETURN

COMPAREMAYORG 
	MOVF  MAYV, W
	SUBWF MAYBV, W
	BTFSS STATUS, C       
	GOTO  NOCHANGEMAY
	GOTO  CHANGEMAY	                        

CHANGEMAY
	MOVF  MAYBG, W 
        MOVWF MAYG
        MOVF  MAYBV, W
        MOVWF MAYV
	RETURN

NOCHANGEMAY
	RETURN
	
COMPAREMENORG 
	MOVF  MENV, W
	SUBWF MENBV, W
	BTFSS STATUS, C  
	GOTO  CHANGEMEN     
	GOTO  NOCHANGEMEN	                        

CHANGEMEN
	MOVF  MENBG, W 
        MOVWF MENG
        MOVF  MENBV, W
        MOVWF MENV
	RETURN

NOCHANGEMEN
	RETURN
	
	
DELAY_D
	movlw	0x87
	movwf	d1
	movlw	0x14
	movwf	d2
DELAY_D_0
	decfsz	d1, f
	goto	$+2
	decfsz	d2, f
	goto	DELAY_D_0

			;2 cycles
	goto	$+1
	RETURN