
DATO EQU 0X21

INICIO 
        ORG     0X00
        GOTO    START
START   
        BSF     STATUS, 5
        CLRF    TRISB

        BSF     TRISC, 7
        BSF     TRISC, 6
        BSF     TRISC, 5
        BSF     TRISC, 4
        BSF     TRISC, 2
        BSF     TRISC, 3

	BCF	STATUS, RP0 
        MOVLW   0X00
        MOVWF   PORTB


DECODIFICADOR
        BTFSC   PORTC, 7
        GOTO    OCHOYNUEVE
	BTFSC	PORTC, 6
	GOTO	CUATROASIETE
	GOTO	CEROATRES
	GOTO	DECODIFICADOR

CEROATRES
	BTFSC	PORTC, 5
	GOTO	DOSYTRES
	GOTO	CEROYUNO
	GOTO	DECODIFICADOR
CEROYUNO
	BTFSC	PORTC, 	4
	GOTO	UNO
	MOVLW	B'01011111'
	MOVWF	DATO
	CALL	MV
	GOTO	DECODIFICADOR

UNO
	MOVLW	B'00000110'
	MOVWF	DATO
	CALL	MV
	GOTO	DECODIFICADOR
DOSYTRES
	BTFSC	PORTC, 	4
	GOTO	TRES
	MOVLW	B'00111011'
	MOVWF	DATO
	CALL	MV
	GOTO	DECODIFICADOR
TRES	
	MOVLW	B'00101111'
	MOVWF	DATO
	CALL	MV
	GOTO    DECODIFICADOR
MV	
	MOVF	DATO, W  ; A DONDE, DESDE DONDE
	MOVWF	PORTB	
	RETURN

CUATROASIETE	
	BTFSC	PORTC, 5
	GOTO	SEISYSIETE
	GOTO	CINCOYCUATRO
	GOTO	DECODIFICADOR
CINCOYCUATRO
	BTFSC	PORTC, 4
	GOTO	CINCO
        MOVLW	B'01100110';SEIS
	MOVWF	DATO
	CALL	MV
	GOTO	DECODIFICADOR
CINCO
        MOVLW	B'01101101'
	MOVWF	DATO
	CALL	MV
	GOTO	DECODIFICADOR
	
SEISYSIETE	
	BTFSC	PORTC, 4
	GOTO	SIETE
        MOVLW	B'01111101';SEIS
	MOVWF	DATO
	CALL	MV
	GOTO	DECODIFICADOR
SIETE
        MOVLW	B'00000111'
	MOVWF	DATO
	CALL	MV
	GOTO	DECODIFICADOR

OCHOYNUEVE
        BTFSS   PORTC, 4
        GOTO    OCHO
        MOVLW	B'01101111';NUEVE
	MOVWF	DATO
	CALL	MV
	GOTO	DECODIFICADOR
OCHO
	MOVLW	B'01111111'
	MOVWF	DATO
	CALL	MV
	GOTO    DECODIFICADOR